[package]
edition = "2024"
name = "s3-display-gyro-test-rs"
version = "0.1.0"

[[bin]]
name = "s3-display-gyro-test-rs"
path = "./src/bin/main.rs"

[dependencies]
esp-hal = { version = "1.1.1", features = ["esp32s3", "log-04", "unstable"] }

esp-rtos = { version = "0.3.0", features = [
  "embassy",
  "esp-alloc",
  "esp32s3",
  "log-04",
] }

esp-bootloader-esp-idf = { version = "0.5.0", features = ["esp32s3", "log-04"] }
log = "0.4.32"

embassy-executor = { version = "0.10.0", features = ["log"] }
embassy-time = { version = "0.5.1", features = ["log"] }
embassy-sync = { version = "0.8.0" }
esp-alloc = "0.10.0"
esp-backtrace = { version = "0.19.0", features = [
  "esp32s3",
  "panic-handler",
  "println",
] }
esp-println = { version = "0.17.0", features = ["esp32s3", "log-04"] }

critical-section = "1.2.0"
static_cell = "2.1.1"

mipidsi = "0.10.0"
# Display dependencies
embedded-graphics = "0.8.2"
embedded-text = "0.7.3"

# Sensor dependencies
bmi160 = "1.1.0"
embedded-hal = "1.0.0"
embedded-hal-bus = "0.3.0"
anyhow = { version = "1.0.102", default-features = false }


[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units = 1        # LLVM can perform better optimizations using a single thread
debug = 2
debug-assertions = false
incremental = false
lto = 'thin'
opt-level = 's'
overflow-checks = false
